### ISSUE TITLE
Directory is deleted at the end

### ISSUE THREAD

**Issue by dianamosa** [hillerlab/TOGA#132] opened 2023-12-20 22:11 UTC
Hello, I am trying to run TOGA (the most recent version on Github) and everything runs perfect until the Cleanup step (STEP 11).  Once the script finish, it deletes the entire directory where I am working. This happened with my real data and the test data. 
As everything is deleted I cannot recover the log information, but this is the last step I was able to recover from TOGA:

`
orthology_mapping: Extracted 1161 orthology components in total
orthology_mapping: Orthology class sizes:
* one2one: 993
* one2zero: 87
* one2many: 43
* many2many: 20
* many2one: 18
orthology_mapping: saving the results to /global/scratch/toga_test/mm10_annotation_toga/orthology_classification.tsv

#### STEP 11: Cleanup: merge parallel steps output files
Traceback (most recent call last):
  File "/global/scratch/software/TOGA/toga.py", line 1742, in <module>
    main()
  File "/global/scratch/software/TOGA/toga.py", line 1738, in main
    toga_manager.run()
  File "/global/scratch/software/TOGA/toga.py", line 679, in run
    self.__left_done_mark()
  File "/global/scratch/software/TOGA/toga.py", line 1398, in __left_done_mark
    f = open(mark_file, "w")
FileNotFoundError: [Errno 2] No such file or directory: 
`

I don't know if this is a bug or something, have you seen this before?

I ran the test  as follows:

`
WD=$(pwd)

toga.py hg38.mm10.chr11.chain hg38.genCode27.chr11.bed ${REFERENCE}.2bit ${QUERY}.2bit --kt --pn ${QUERY}_annotation -i ${TOGA}/supply/hg38.v35.for_toga.isoforms.tsv --nc ${TOGA}/nextflow_config_files/ --cb 3,5 --cjn 500 --u12 ${TOGA}/supply/hg38.U12sites.tsv --chn 150 --ms --gp mirang --nd ${WD}
`

Thanks!

**Comment by MichaelHiller** [comment] 2023-12-21 07:36
This is highly unusual. 
@kirilenkobm Can you pls have a look?

**Comment by kirilenkobm** [comment] 2023-12-27 16:04
Hi @dianamosa this is definitely a bug, however, if must not affect the pipeline results.
Thanks for reporting it.

**Comment by kirilenkobm** [comment] 2024-01-12 17:50
Deleted my previous comment because I misinterpreted the issue at first.
@dianamosa the issue is `--nd ${WD}`
`--nd` is suppose to be a temporary directory to store nextflow logs, which are deleted after TOGA run.
I should write some guard to prevent assigning it to PWD, TOGA output dir, and other dangerous places.

**Comment by kirilenkobm** [comment] 2024-01-17 20:03
Must be fixed now: https://github.com/hillerlab/TOGA/commit/3eca397022afeb6797e0881a0c8bf27e9570237e
Added a little guard to prevent assigning temp directories to useful locations

**Closed by kirilenkobm** 2024-01-17 20:03 UTC
Labels: bug, enhancement, code improvements
