### ISSUE TITLE
#### STEP 4: Classify chains using gradient boosting model - fails

### ISSUE THREAD

**Issue by gaurav-agavekar** [hillerlab/TOGA#17] opened 2021-04-26 08:08 UTC
Hello,

First of all, thank you for your efforts in developing TOGA.

I'm trying to get TOGA to work on our cluster that uses SLURM.

I created a new conda environment for TOGA and installed all the dependencies as instructed, including training xgboost models and installing CESAR. It all seems to have worked OK until Step 3 but I get following error at STEP 4 when running the "micro" test:

#### STEP 4: Classify chains using gradient boosting model

Decision tree in progress...
Loading dataset...

Load and apply model

Traceback (most recent call last):
  File "./toga.py", line 1270, in <module>
    main()
  File "./toga.py", line 1266, in main
    toga_manager.run()
  File "./toga.py", line 572, in run
    self.__classify_chains()
  File "./toga.py", line 726, in __classify_chains
    annot_threshold=self.orth_score_threshold)
  File "/flash/EconomoU/gaurav/apps/TOGA/modules/classify_chains.py", line 134, in classify_chains
    se_pred = se_model.predict_proba(X_se)[:, 1]
IndexError: index 1 is out of bounds for axis 1 with size 0

I browsed through Issues here and it seems somewhat similar to [this](https://github.com/hillerlab/TOGA/issues/8). I'm not sure however how to find out if different versions of numpy/scikit-learn are being used when training the model and running the micro test.

Do you have any suggestions for how I could fix this? Thank you~

**Comment by kirilenkobm** [comment] 2021-05-13 17:38
Duplicate of this issue: https://github.com/hillerlab/TOGA/issues/18

Fixed now, thanks for your feedback!

- Bogdan

**Closed by kirilenkobm** 2021-05-13 17:38 UTC

**Comment by gaurav-agavekar** [comment] 2021-05-25 01:22
Thanks for the fix, Bogdan. I reran the micro test and this time it went up to Step 10 but failed with following error: 

Traceback (most recent call last):
  File "./toga.py", line 1270, in <module>
    main()
  File "./toga.py", line 1266, in main
    toga_manager.run()
  File "./toga.py", line 603, in run
    self.__orthology_type_map()
  File "./toga.py", line 1054, in __orthology_type_map
    get_query_isoforms_data(self.query_annotation, query_isoforms_file, save_genes_track=query_gene_spans)
  File "/flash/EconomoU/gaurav/apps/TOGA/modules/make_query_isoforms.py", line 243, in get_query_isoforms_data
    components = get_graph_components(conn_graph)
  File "/flash/EconomoU/gaurav/apps/TOGA/modules/common.py", line 251, in get_graph_components
    nx_v = float(nx.__version__)
ValueError: could not convert string to float: '2.5.1'

Since this was just a potential warning about networkx version, I commented it out in common.py and got TOGA to work. But maybe you could use strip(), instead of float()?

Gaurav
